version: '3.4'

services:
  splunk-apm-dotnetcore-example:
    image: ${DOCKER_REGISTRY-}splunkapmdotnetcoreexample:test
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8888:80
    environment:
      - SIGNALFX_ENV=docker-compose-local
      - SIGNALFX_ACCESS_TOKEN=${SPLUNK_TOKEN}
      - SIGNALFX_ENDPOINT_URL=https://ingest.${SPLUNK_REALM}.signalfx.com/v2/trace
      - SIGNALFX_TRACE_DEBUG=true
      - SIGNALFX_STDOUT_LOG_ENABLED=true
      - SIGNALFX_LOGS_INJECTION=true