---
apiVersion: v1
kind: Service
metadata:
  name: aspnet-mvc-dotnetcore-example
spec:
  type: ClusterIP
  selector:
    app: aspnet-mvc-dotnetcore-example
  ports:
  - name: http
    port: 80
    targetPort: 80
